-- Ejecutar en Supabase SQL Editor. Es idempotente para una instalación nueva.
create type public.rol_usuario as enum ('director', 'administrativo', 'maestro');
create type public.turno_escolar as enum ('Matutino', 'Vespertino');
create type public.tipo_asistencia as enum ('asistencia', 'retardo', 'falta', 'salida_autorizada');

create table public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  email text not null unique,
  rol public.rol_usuario not null,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.grupos (
  id bigint generated by default as identity primary key,
  grado text not null,
  grupo text not null,
  turno public.turno_escolar not null default 'Matutino',
  aula text,
  maestro_id uuid references public.usuarios(id) on delete set null,
  activo boolean not null default true,
  unique (grado, grupo, turno)
);

create table public.alumnos (
  id bigint generated by default as identity primary key,
  nombre_completo text not null,
  matricula text unique,
  grado text not null,
  grupo text not null,
  turno public.turno_escolar not null default 'Matutino',
  tutor text,
  telefono text,
  observaciones text,
  huella_id text unique,
  activo boolean not null default true,
  ultimo_acceso timestamptz,
  ultimo_lector_id bigint,
  created_at timestamptz not null default now()
);

create table public.lectores (
  id bigint generated by default as identity primary key,
  codigo text unique,
  nombre text not null,
  ubicacion text not null,
  ip inet,
  modelo text not null default 'ZKTeco M2-LR',
  estado text not null default 'desconectado' check (estado in ('conectado', 'desconectado')),
  ultima_conexion timestamptz,
  ultima_lectura timestamptz,
  created_at timestamptz not null default now()
);

alter table public.alumnos
  add constraint alumnos_ultimo_lector_fk foreign key (ultimo_lector_id) references public.lectores(id) on delete set null;

create table public.asistencias (
  id bigint generated by default as identity primary key,
  alumno_id bigint not null references public.alumnos(id) on delete restrict,
  fecha date not null default current_date,
  hora time not null default localtime,
  tipo public.tipo_asistencia not null,
  lector_id bigint references public.lectores(id) on delete set null,
  motivo text,
  autorizado_por text,
  created_at timestamptz not null default now()
);

create index alumnos_grupo_idx on public.alumnos(grado, grupo, turno);
create index asistencias_fecha_idx on public.asistencias(fecha, tipo);
create index asistencias_alumno_idx on public.asistencias(alumno_id, fecha);

alter table public.usuarios enable row level security;
alter table public.grupos enable row level security;
alter table public.alumnos enable row level security;
alter table public.asistencias enable row level security;
alter table public.lectores enable row level security;

create or replace function public.es_personal()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.usuarios where id = auth.uid() and rol in ('director','administrativo') and activo); $$;

create policy "usuario ve su perfil" on public.usuarios for select to authenticated
using (id = auth.uid() or public.es_personal());
create policy "personal gestiona usuarios" on public.usuarios for all to authenticated
using (public.es_personal()) with check (public.es_personal());

create policy "personal gestiona grupos" on public.grupos for all to authenticated
using (public.es_personal()) with check (public.es_personal());
create policy "maestro ve sus grupos" on public.grupos for select to authenticated
using (maestro_id = auth.uid());

create policy "personal gestiona alumnos" on public.alumnos for all to authenticated
using (public.es_personal()) with check (public.es_personal());
create policy "maestro ve alumnos asignados" on public.alumnos for select to authenticated
using (exists(select 1 from public.grupos g where g.maestro_id = auth.uid() and g.grado = alumnos.grado and g.grupo = alumnos.grupo and g.turno = alumnos.turno));

create policy "personal gestiona asistencias" on public.asistencias for all to authenticated
using (public.es_personal()) with check (public.es_personal());
create policy "maestro ve asistencias asignadas" on public.asistencias for select to authenticated
using (exists(select 1 from public.alumnos a join public.grupos g on g.grado=a.grado and g.grupo=a.grupo and g.turno=a.turno where a.id=asistencias.alumno_id and g.maestro_id=auth.uid()));

create policy "personal gestiona lectores" on public.lectores for all to authenticated
using (public.es_personal()) with check (public.es_personal());
